app/src/main/res/values-pt-rBR/arrays.xml, app/src/main/res/values-pt-rBR/strings.xml
Hi @VREMSoftwareDevelopment . I added a brazilian portuguese translation.
Feel free to merge ;)
--
'Akira
=> --added brazilian portuguese translation (values-pt-rBR/arrays.xml; values.xml)

app/src/main/res/values-de/arrays.xml, app/src/main/res/values-de/strings.xml
Hello,
I wasn't able to translate three strings:
- _channel_rating_best_alternative_ and _channel_rating_best_none_:
- Where can I find them in the app?
- action_vendors
- What do you mean by "Vendors"? The app doesn't display any data for me.
=> Added German translation

app/src/main/res/values-de/strings.xml
Google Translate isn't perfect :smile:
=> improved German translation

app/src/main/res/values-ru/arrays.xml, app/src/main/res/values-ru/strings.xml
Here is the correct translation into Russian.
=> Here is the correct translation into Russian

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/arrays.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh/strings.xml
I've added italian translation and also removed translation of 'app_company_name' from the others lang files, since it's marked as untranslatable
=> Added Italian translation

app/src/main/res/values-it/arrays.xml, app/src/main/res/values-it/strings.xml
I've fixed some translations that were wrong.
"Apply filter" was translated as "Clear filter", so a new update in the play store is needed asap.
=> Fix for italian translation

app/build.properties, app/src/main/res/values-pt/arrays.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
Partially addresses issue #124
=> Update Brazilian Portuguese translation

app/src/main/AndroidManifest.xml, app/src/main/java/com/vrem/wifianalyzer/MainActivity.java, app/src/main/java/com/vrem/wifianalyzer/MainReload.java, app/src/main/java/com/vrem/wifianalyzer/settings/LanguageCountry.java, app/src/main/java/com/vrem/wifianalyzer/settings/LanguagePreference.java, app/src/main/java/com/vrem/wifianalyzer/settings/LocaleContextWrapper.java, app/src/main/java/com/vrem/wifianalyzer/settings/LocaleType.java, app/src/main/java/com/vrem/wifianalyzer/settings/SettingActivity.java, app/src/main/java/com/vrem/wifianalyzer/settings/Settings.java, app/src/main/java/com/vrem/wifianalyzer/wifi/band/WiFiChannelCountry.java, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/com/vrem/wifianalyzer/MainReloadTest.java, app/src/test/java/com/vrem/wifianalyzer/settings/LanguagePreferenceTest.java, app/src/test/java/com/vrem/wifianalyzer/settings/LocaleTypeTest.java, app/src/test/java/com/vrem/wifianalyzer/settings/SettingsTest.java
This is an attempt to fix the second part of issue #124.
This change adds another option in the SettingActivity which allows
the user to select a language. Currently, this is only a proof of
concept and is only implemented for German and English, as I didn't
find a way to automatically determine all available translations yet
(i.e. all languages for which values-XX exists) - if anyone knows
how to do that in a generic way, please let me know and I'll
implement this.
Also, if there's a nicer way to do this, let me know, this is my
first attempt at playing around with Android apps.
=> [Work in Progress] Allow language to be changed in Settings

app/src/main/res/values-es/strings.xml
Little changes, copyright year changed to 2018. Thanks guys for your work.
=> Updated Spanish strings file

app/src/main/res/values-pl/arrays.xml, app/src/main/res/values-pl/strings.xml
=> TW Completing Polish translations

app/src/main/res/values-de/strings.xml
- Updated German Strings
-none
Operating System: Lineage OS 15.1 (Android 8.1), Android Preview SDK 28, Android 7.1.1, Android 8.0 (and of cause the emulator in this case android P again)
Platform: -
Target Platform: -
Toolchain Version: -
SDK Version: 27, 28, 25,26
=> updated German Strings

app/src/main/res/values-zh-rCN/strings.xml
set security_none to  未加密
set filter_title to 过滤器
- Platform:
- SDK Version:
=> update Chinese translation

app/src/main/res/values-zh-rCN/strings.xml
update Chinese translation.
**Please make sure that you are using `feature` branch, since all the WiFi Analyzer changes are done on the `feature` branch!**
- Platform:
- SDK Version:
=> update Chinese translation of strings.xml

app/src/main/res/values-bg/strings.xml
- Add Bulgarian translation
No
=> Add Bulgarian language

app/src/main/res/values-uk/strings.xml
=> Ukrainian language

app/src/main/res/values-nl/strings.xml
A few grammer, spelling and consistency errors have been resolved.
**Please make sure that you are using `feature` branch, since all the WiFi Analyzer changes are done on the `feature` branch!**
- Platform:
- SDK Version:
=> Dutch language corrections

app/src/main/res/values-it/strings.xml
As title says, I've fixed some incorrect translations.
=> Italian translations update

app/src/main/res/values-zh-rCN/strings.xml
**Please make sure that you are using `feature` branch, since all the WiFi Analyzer changes are done on the `feature` branch!**
- Platform:
- SDK Version:
=> Update Strings for Zh-rCN

README.md
https://www.duckware.com/tech/wifi-in-the-us.html
**Please make sure that you are using `feature` branch, since all the WiFi Analyzer changes are done on the `feature` branch!**
- Platform:
- SDK Version:
=> added a useful link

app/src/main/res/values-el/strings.xml
=> Greek translation

app/src/main/res/values-pt-rBR/strings.xml, fastlane/metadata/android/pt-BR/full_description.txt
- "banda" -> "frequência"
- Frequência de Wi-Fi -> Frequência do Wi-Fi
- caixa da letra -> letras maiúsculas
last one (before new strings are added)
=> translation: pt-BR: small fixes
